package main

// Generated by https://quicktype.io

type Role struct {
	ID      int64    `json:"id"`
	Name    string   `json:"name"`
	Summary string   `json:"summary"`
	Skills  []Skills `json:"skills"`
}

type Skills struct {
	ID   int64     `json:"id"`
	Type SkillType `json:"type"`
	Name string    `json:"name"`
}

type SkillType string

const (
	MartialArts SkillType = "武學"
	Magic       SkillType = "法術"
)

var Data []Role

func init() {
	Data = []Role{
		Role{
			ID:      1,
			Name:    "阿修羅",
			Summary: "死國魖族最強者，在歷經多場戰役統一死國，直接挑戰天者權威，不服其領導，要求讓三族和平共處，因此被天者以增加資源為名，前往打通連接火宅佛獄、死國及苦境的莫汗走廊，未料在工程半途被楓岫主人所乘駕的隕石撞毀，阿修羅在天者刻意算計下意外身亡，身葬苦境與死國間的異次元。",
			Skills: []Skills{
				Skills{ID: 1, Type: MartialArts, Name: "天之爆"},
				Skills{ID: 2, Type: MartialArts, Name: "魔之狂"},
				Skills{ID: 3, Type: MartialArts, Name: "天之渦"},
				Skills{ID: 4, Type: MartialArts, Name: "闇之爆"},
				Skills{ID: 5, Type: Magic, Name: "山河凝元·天地共引"},
				Skills{ID: 6, Type: Magic, Name: "地之火·九天滅絕"},
			},
		},
		Role{
			ID:      2,
			Name:    "白塵子",
			Summary: "火宅佛獄凱旋侯的副體之一，本名黑枒君，臥底中原武林，向佛獄通風報信，最後被素還真所殺並冒充其身份一探佛獄之秘。",
			Skills: []Skills{
				Skills{ID: 7, Type: MartialArts, Name: "凝宇化空"},
				Skills{ID: 8, Type: MartialArts, Name: "反神源"},
			},
		},
	}
}
